### ISSUE TITLE
OneToOne selfKey side issue

### ISSUE THREAD

**Issue by davmik2601** [tailoredmedia/backend-nx-skeleton#6]
https://github.com/tailoredmedia/backend-nx-skeleton/blob/d2eed2e2dc90782c9845e05ef4c75cd733790abb/packages/nestjs-graphql-typeorm-dataloader/src/loader-handlers/self-key.handler.ts#L15

`return dataloader.load(columns[0].getEntityValue(parent))[0] ?? null`

This is an big issue, I need this correction,   

dataloader.load(columns[0].getEntityValue(parent))  is undefined and so returned null, 

`return (await dataloader.load(columns[0].getEntityValue(parent)))[0] ?? null `   this is work, please update this,  @cenk1cenk2 
Thanks Dear @cenk1cenk2

**Comment by cenk1cenk2** [comment]
Hey @davmik2601,

Thank you for the information, I have also seen your mails but was not directly on the computer so did not get the change to reply. 

Thanks for figuring out the issue, since it has been some time since I have published/used this library, I have been a little bit out of context. A new version will be released with your aforementioned fix.

**Comment by davmik2601** [comment]
> Hey @davmik2601,
> 
> Thank you for the information, I have also seen your mails but was not directly on the computer so did not get the change to reply.
> 
> Thanks for figuring out the issue, since it has been some time since I have published/used this library, I have been a little bit out of context. A new version will be released with your aforementioned fix.

Thank You too @cenk1cenk2. And When will be released the new version?

**Comment by cenk1cenk2** [comment]
[W] [release] npm notice package: @webundsoehne/nestjs-graphql-typeorm-dataloader@4.0.6

Should be already out.
